ARG PYTHON_VERSION="3.9"
FROM python3.9-obs AS python-obs-builder

FROM python:${PYTHON_VERSION} AS python-builder

COPY --from=python-obs-builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

WORKDIR /src